# Generated by Django 4.2.19 on 2025-03-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerquery',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerquery',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
