# Generated by Django 4.2.19 on 2025-03-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0002_alter_farmerquery_contact_alter_farmerquery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
